use git2::{Delta, Diff, DiffFormat, DiffOptions, IndexAddOption, Repository, Signature};
use std::path::{Path, PathBuf};
use thiserror::Error;

const MEMORY_BASELINE_COMMIT_MESSAGE: &str = "Memory workspace baseline";
const MEMORY_WORKSPACE_DIFF_MAX_BYTES: usize = 200_000;

#[derive(Debug, Error)]
pub enum MemoryWorkspaceGitError {
    #[error("Failed to create memory workspace {root}: {source}")]
    CreateRoot {
        root: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("Failed to inspect memory workspace git metadata {path}: {source}")]
    InspectGitMetadata {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("Failed to remove memory workspace git metadata {path}: {source}")]
    RemoveGitMetadata {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("Failed to read added memory workspace file {path}: {source}")]
    ReadAddedFile {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("Memory workspace git operation {operation} failed in {root}: {source}")]
    GitOperation {
        root: PathBuf,
        operation: &'static str,
        #[source]
        source: git2::Error,
    },
    #[error("Memory workspace diff output was not UTF-8: {source}")]
    DiffOutputUtf8 {
        #[source]
        source: std::string::FromUtf8Error,
    },
    #[error("Memory workspace git task failed: {source}")]
    Join {
        #[source]
        source: tokio::task::JoinError,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MemoryWorkspaceChangeStatus {
    Added,
    Modified,
    Deleted,
}

impl MemoryWorkspaceChangeStatus {
    pub fn label(self) -> &'static str {
        match self {
            Self::Added => "A",
            Self::Modified => "M",
            Self::Deleted => "D",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MemoryWorkspaceChange {
    pub status: MemoryWorkspaceChangeStatus,
    pub path: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MemoryWorkspaceDiff {
    pub changes: Vec<MemoryWorkspaceChange>,
    pub unified_diff: String,
}

impl MemoryWorkspaceDiff {
    pub fn has_changes(&self) -> bool {
        !self.changes.is_empty()
    }
}

pub async fn ensure_memory_workspace_git_baseline(
    root: &Path,
) -> Result<(), MemoryWorkspaceGitError> {
    let root = root.to_path_buf();
    tokio::task::spawn_blocking(move || {
        create_root(&root)?;

        if root.join(".git").is_dir() {
            if let Ok(repository) = Repository::open(&root) {
                if repository.head().is_ok() {
                    return Ok(());
                }
            }
        }

        reset_memory_workspace_git_baseline_sync(&root)
    })
    .await
    .map_err(|source| MemoryWorkspaceGitError::Join { source })?
}

pub async fn reset_memory_workspace_git_baseline(
    root: &Path,
) -> Result<(), MemoryWorkspaceGitError> {
    let root = root.to_path_buf();
    tokio::task::spawn_blocking(move || reset_memory_workspace_git_baseline_sync(&root))
        .await
        .map_err(|source| MemoryWorkspaceGitError::Join { source })?
}

pub async fn memory_workspace_diff(
    root: &Path,
) -> Result<MemoryWorkspaceDiff, MemoryWorkspaceGitError> {
    let root = root.to_path_buf();
    tokio::task::spawn_blocking(move || memory_workspace_diff_sync(&root))
        .await
        .map_err(|source| MemoryWorkspaceGitError::Join { source })?
}

pub fn render_memory_workspace_diff_file(diff: &MemoryWorkspaceDiff) -> String {
    let mut rendered = String::from(
        "# Memory Workspace Diff\n\n\
         Generated by BitFun before Phase 2 memory consolidation. Read this file first and do not edit it.\n\n\
         ## Status\n",
    );

    if !diff.has_changes() {
        rendered.push_str("- none\n");
        return rendered;
    }

    for change in &diff.changes {
        rendered.push_str(&format!("- {} {}\n", change.status.label(), change.path));
    }
    rendered.push_str("\n## Diff\n\n```diff\n");
    append_bounded_diff(&mut rendered, &diff.unified_diff);
    rendered.push_str("```\n");
    rendered
}

fn create_root(root: &Path) -> Result<(), MemoryWorkspaceGitError> {
    std::fs::create_dir_all(root).map_err(|source| MemoryWorkspaceGitError::CreateRoot {
        root: root.to_path_buf(),
        source,
    })
}

fn reset_memory_workspace_git_baseline_sync(root: &Path) -> Result<(), MemoryWorkspaceGitError> {
    create_root(root)?;
    remove_git_metadata(root)?;
    let repository = Repository::init(root)
        .map_err(|source| git_operation(root, "initialize repository", source))?;
    let mut index = repository
        .index()
        .map_err(|source| git_operation(root, "open repository index", source))?;
    index
        .add_all(["*"].iter(), IndexAddOption::DEFAULT, None)
        .map_err(|source| git_operation(root, "stage workspace files", source))?;
    index
        .write()
        .map_err(|source| git_operation(root, "write repository index", source))?;
    let tree_id = index
        .write_tree()
        .map_err(|source| git_operation(root, "write baseline tree", source))?;
    let tree = repository
        .find_tree(tree_id)
        .map_err(|source| git_operation(root, "load baseline tree", source))?;
    let signature = Signature::now("BitFun", "bitfun@localhost")
        .map_err(|source| git_operation(root, "create baseline signature", source))?;
    repository
        .commit(
            Some("HEAD"),
            &signature,
            &signature,
            MEMORY_BASELINE_COMMIT_MESSAGE,
            &tree,
            &[],
        )
        .map_err(|source| git_operation(root, "commit baseline", source))?;
    Ok(())
}

fn remove_git_metadata(root: &Path) -> Result<(), MemoryWorkspaceGitError> {
    let path = root.join(".git");
    let metadata = match std::fs::symlink_metadata(&path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(source) => {
            return Err(MemoryWorkspaceGitError::InspectGitMetadata { path, source });
        }
    };

    let result = if metadata.is_dir() && !metadata.file_type().is_symlink() {
        std::fs::remove_dir_all(&path)
    } else {
        std::fs::remove_file(&path)
    };

    result.map_err(|source| MemoryWorkspaceGitError::RemoveGitMetadata { path, source })
}

fn memory_workspace_diff_sync(root: &Path) -> Result<MemoryWorkspaceDiff, MemoryWorkspaceGitError> {
    let repository =
        Repository::open(root).map_err(|source| git_operation(root, "open repository", source))?;
    let head = repository
        .head()
        .map_err(|source| git_operation(root, "resolve baseline HEAD", source))?;
    let baseline = head
        .peel_to_tree()
        .map_err(|source| git_operation(root, "load baseline tree", source))?;
    let mut options = DiffOptions::new();
    options
        .include_untracked(true)
        .recurse_untracked_dirs(true)
        .include_ignored(true)
        .recurse_ignored_dirs(true)
        .show_untracked_content(true)
        .include_typechange(true);
    let diff = repository
        .diff_tree_to_workdir_with_index(Some(&baseline), Some(&mut options))
        .map_err(|source| git_operation(root, "compute workspace diff", source))?;
    let changes = collect_workspace_changes(&diff);
    let mut unified_diff = render_workspace_diff(&diff, root)?;
    for path in ignored_workspace_paths(&diff) {
        // libgit2 reports ignored entries but does not render their content as a
        // patch, while the previous filesystem scan included every file except
        // `.git`. Append an equivalent added-file patch to preserve that input.
        unified_diff.push_str(&render_added_file_diff(root, &path)?);
    }

    Ok(MemoryWorkspaceDiff {
        changes,
        unified_diff,
    })
}

fn collect_workspace_changes(diff: &Diff<'_>) -> Vec<MemoryWorkspaceChange> {
    let mut changes = Vec::new();
    for delta in diff.deltas() {
        let (status, path) = match delta.status() {
            Delta::Added | Delta::Untracked | Delta::Ignored => {
                (MemoryWorkspaceChangeStatus::Added, delta.new_file().path())
            }
            Delta::Deleted => (
                MemoryWorkspaceChangeStatus::Deleted,
                delta.old_file().path(),
            ),
            Delta::Modified
            | Delta::Renamed
            | Delta::Copied
            | Delta::Typechange
            | Delta::Unreadable
            | Delta::Conflicted => (
                MemoryWorkspaceChangeStatus::Modified,
                delta.new_file().path().or_else(|| delta.old_file().path()),
            ),
            Delta::Unmodified => continue,
        };
        if let Some(path) = path {
            changes.push(MemoryWorkspaceChange {
                status,
                path: path.to_string_lossy().replace('\\', "/"),
            });
        }
    }
    changes.sort_by(|left, right| left.path.cmp(&right.path));
    changes.dedup_by(|left, right| left.path == right.path);
    changes
}

fn ignored_workspace_paths(diff: &Diff<'_>) -> Vec<String> {
    let mut paths = diff
        .deltas()
        .filter(|delta| delta.status() == Delta::Ignored)
        .filter_map(|delta| delta.new_file().path())
        .map(|path| path.to_string_lossy().replace('\\', "/"))
        .collect::<Vec<_>>();
    paths.sort();
    paths.dedup();
    paths
}

fn render_added_file_diff(root: &Path, path: &str) -> Result<String, MemoryWorkspaceGitError> {
    let file_path = root.join(path);
    let body = std::fs::read_to_string(&file_path).map_err(|source| {
        MemoryWorkspaceGitError::ReadAddedFile {
            path: file_path,
            source,
        }
    })?;
    let diff = similar::TextDiff::from_lines("", &body);
    let mut rendered = format!(
        "diff --git a/{path} b/{path}\nnew file mode 100644\n--- /dev/null\n+++ b/{path}\n"
    );
    for change in diff.iter_all_changes() {
        let sign = match change.tag() {
            similar::ChangeTag::Delete => "-",
            similar::ChangeTag::Insert => "+",
            similar::ChangeTag::Equal => " ",
        };
        rendered.push_str(sign);
        rendered.push_str(change.value());
    }
    if !rendered.ends_with('\n') {
        rendered.push('\n');
    }
    Ok(rendered)
}

fn render_workspace_diff(diff: &Diff<'_>, root: &Path) -> Result<String, MemoryWorkspaceGitError> {
    let mut rendered = Vec::new();
    diff.print(DiffFormat::Patch, |_, _, line| {
        if matches!(line.origin(), ' ' | '+' | '-') {
            rendered.push(line.origin() as u8);
        }
        rendered.extend_from_slice(line.content());
        true
    })
    .map_err(|source| git_operation(root, "render workspace diff", source))?;
    String::from_utf8(rendered).map_err(|source| MemoryWorkspaceGitError::DiffOutputUtf8 { source })
}

fn append_bounded_diff(rendered: &mut String, diff: &str) {
    if diff.len() <= MEMORY_WORKSPACE_DIFF_MAX_BYTES {
        rendered.push_str(diff);
        if !diff.ends_with('\n') {
            rendered.push('\n');
        }
        return;
    }

    let boundary = previous_char_boundary(diff, MEMORY_WORKSPACE_DIFF_MAX_BYTES);
    rendered.push_str(&diff[..boundary]);
    if !rendered.ends_with('\n') {
        rendered.push('\n');
    }
    rendered.push_str(&format!(
        "\n[workspace diff truncated at {} bytes]\n",
        MEMORY_WORKSPACE_DIFF_MAX_BYTES
    ));
}

fn previous_char_boundary(value: &str, max_bytes: usize) -> usize {
    if max_bytes >= value.len() {
        return value.len();
    }
    let mut index = max_bytes;
    while !value.is_char_boundary(index) {
        index -= 1;
    }
    index
}

fn git_operation(
    root: &Path,
    operation: &'static str,
    source: git2::Error,
) -> MemoryWorkspaceGitError {
    MemoryWorkspaceGitError::GitOperation {
        root: root.to_path_buf(),
        operation,
        source,
    }
}

#[cfg(test)]
mod tests {
    use super::{
        memory_workspace_diff, render_memory_workspace_diff_file,
        reset_memory_workspace_git_baseline, MemoryWorkspaceChange, MemoryWorkspaceChangeStatus,
    };

    #[tokio::test]
    async fn memory_workspace_git_diff_detects_added_modified_and_deleted_paths() {
        let temp = tempfile::tempdir().unwrap();
        let root = temp.path();
        std::fs::write(root.join("MEMORY.md"), "old index\n").unwrap();
        std::fs::write(root.join("memory_summary.md"), "old summary\n").unwrap();

        reset_memory_workspace_git_baseline(root).await.unwrap();

        std::fs::write(root.join("MEMORY.md"), "new index\n").unwrap();
        std::fs::remove_file(root.join("memory_summary.md")).unwrap();
        std::fs::create_dir_all(root.join("rollout_summaries")).unwrap();
        std::fs::write(
            root.join("rollout_summaries").join("new.md"),
            "new summary\n",
        )
        .unwrap();

        let diff = memory_workspace_diff(root).await.unwrap();

        assert!(diff.has_changes());
        assert!(diff.changes.contains(&MemoryWorkspaceChange {
            status: MemoryWorkspaceChangeStatus::Modified,
            path: "MEMORY.md".to_string(),
        }));
        assert!(diff.changes.contains(&MemoryWorkspaceChange {
            status: MemoryWorkspaceChangeStatus::Deleted,
            path: "memory_summary.md".to_string(),
        }));
        assert!(diff.changes.contains(&MemoryWorkspaceChange {
            status: MemoryWorkspaceChangeStatus::Added,
            path: "rollout_summaries/new.md".to_string(),
        }));
        assert!(diff.unified_diff.contains("diff --git"));
        assert!(diff.unified_diff.contains("+new index"));
        assert!(diff.unified_diff.contains("-old summary"));
        assert!(diff.unified_diff.contains("new index"));
        assert!(diff.unified_diff.contains("new summary"));
    }

    #[tokio::test]
    async fn memory_workspace_diff_includes_ignored_ad_hoc_notes() {
        let temp = tempfile::tempdir().unwrap();
        let root = temp.path();
        std::fs::write(
            root.join(".gitignore"),
            "extensions/ad_hoc/notes/ignored-note.md\n",
        )
        .unwrap();
        reset_memory_workspace_git_baseline(root).await.unwrap();

        let note_path = root.join("extensions/ad_hoc/notes/ignored-note.md");
        std::fs::create_dir_all(note_path.parent().unwrap()).unwrap();
        std::fs::write(&note_path, "Durable ignored memory note\n").unwrap();

        let diff = memory_workspace_diff(root).await.unwrap();

        assert!(diff.changes.contains(&MemoryWorkspaceChange {
            status: MemoryWorkspaceChangeStatus::Added,
            path: "extensions/ad_hoc/notes/ignored-note.md".to_string(),
        }));
        assert!(diff
            .unified_diff
            .contains("extensions/ad_hoc/notes/ignored-note.md"));
        assert!(diff.unified_diff.contains("+Durable ignored memory note"));
    }

    #[test]
    fn memory_workspace_diff_renderer_preserves_legacy_status_header() {
        let rendered = render_memory_workspace_diff_file(&super::MemoryWorkspaceDiff {
            changes: vec![MemoryWorkspaceChange {
                status: MemoryWorkspaceChangeStatus::Added,
                path: "extensions/ad_hoc/notes/example.md".to_string(),
            }],
            unified_diff: "+note\n".to_string(),
        });

        assert!(rendered.contains("# Memory Workspace Diff"));
        assert!(rendered.contains("- A extensions/ad_hoc/notes/example.md"));
        assert!(rendered.contains("```diff\n+note\n```"));
    }
}
